version: "3"
services:
  server:
    image: bookingservice
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/bookingServiceDb?useSSL=false
    networks:
      -  spring-bookingservice-mysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    networks:
      - spring-bookingservice-mysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=bookingServiceDb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234

networks:
  spring-bookingservice-mysql-net: