version: "3"
services:
  server:
    image: routingservice
    ports:
      - "8081:8081"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/routingServiceDb?useSSL=false
    networks:
      -  spring-routingservice-mysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    networks:
      - spring-routingservice-mysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=routingServiceDb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234

networks:
  spring-routingservice-mysql-net:
